[project]
name = "artefact-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.6.9",
    "groq>=1.2.0",
    "openai>=2.38.0",
    "sympy>=1.14.0",
]

[tool.ruff]
line-length = 79

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
select = ["E", "F", "I", "W"]

[tool.ruff.lint.isort]
known-first-party = ["src"]
order-by-type = false

[dependency-groups]
dev = [
    "ruff>=0.15.14",
]
